"""
Layer 9: Capability Registry - Data Models

Defines the core data structures for managing, storing, and querying capabilities
in the SPS-CA system.
"""

from dataclasses import dataclass, asdict, field
from typing import List, Dict, Optional, Any
from datetime import datetime
from enum import Enum


class CapabilityType(str, Enum):
    """Standard capability types."""
    ANALYSIS = "analysis"
    BUG_DETECTION = "bug_detection"
    FIX = "fix"
    GENERATION = "generation"
    OPTIMIZATION = "optimization"
    VALIDATION = "validation"
    PARSING = "parsing"
    TRANSFORMATION = "transformation"
    REFACTORING = "refactoring"
    UNKNOWN = "unknown"


class CapabilityLanguage(str, Enum):
    """Supported programming languages."""
    PYTHON = "python"
    JAVA = "java"
    JAVASCRIPT = "javascript"
    TYPESCRIPT = "typescript"
    GO = "go"
    CSHARP = "csharp"
    CPP = "cpp"
    RUST = "rust"


@dataclass
class CapabilityMetadata:
    """
    Complete metadata for a capability (seed or generated).
    
    Attributes:
        id: Unique capability identifier (CAP-001, CAP-009, etc.)
        name: Human-readable name
        description: What the capability does
        type: CapabilityType (analysis, bug_detection, fix, etc.)
        entry_point: Function name to call (e.g., "analyze_simple_bugs")
        supported_languages: List of target languages the capability handles
        version: Semantic version (e.g., "1.0.0")
        created_date: ISO timestamp when capability was created
        last_modified: ISO timestamp of last modification
        generated: Boolean - True if this capability was generated by Layer 8
        origin: If generated, which mechanism created it (e.g., "capability_evolution")
        failure_pattern: If generated, which failure pattern triggered generation
        trigger_tasks: If generated, list of task IDs that triggered generation
        reuse_count: How many times this capability has been used
        test_coverage: Percentage of code covered by tests (0-100)
        documentation_path: Path to README.md or documentation file
        metadata_path: Path to metadata.json file
        status: "active", "deprecated", or "experimental"
    """
    id: str  # CAP-001, CAP-009, etc.
    name: str
    description: str
    type: CapabilityType
    entry_point: str
    supported_languages: List[str]  # ["python", "java", "javascript"]
    version: str = "1.0.0"
    created_date: str = field(default_factory=lambda: datetime.utcnow().isoformat())
    last_modified: str = field(default_factory=lambda: datetime.utcnow().isoformat())
    generated: bool = False
    origin: Optional[str] = None  # "capability_evolution", "manual", etc.
    failure_pattern: Optional[str] = None  # "parsing_error", "type_mismatch", etc.
    trigger_tasks: List[str] = field(default_factory=list)  # ["task_010", "task_015", "task_020"]
    reuse_count: int = 0
    test_coverage: float = 0.0  # 0-100
    documentation_path: str = ""
    metadata_path: str = ""
    status: str = "active"  # "active", "deprecated", "experimental"
    extra_metadata: Dict[str, Any] = field(default_factory=dict)  # For custom fields
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for JSON serialization."""
        return {
            "id": self.id,
            "name": self.name,
            "description": self.description,
            "type": self.type.value if isinstance(self.type, Enum) else self.type,
            "entry_point": self.entry_point,
            "supported_languages": self.supported_languages,
            "version": self.version,
            "created_date": self.created_date,
            "last_modified": self.last_modified,
            "generated": self.generated,
            "origin": self.origin,
            "failure_pattern": self.failure_pattern,
            "trigger_tasks": self.trigger_tasks,
            "reuse_count": self.reuse_count,
            "test_coverage": self.test_coverage,
            "documentation_path": self.documentation_path,
            "metadata_path": self.metadata_path,
            "status": self.status,
            "extra_metadata": self.extra_metadata,
        }
    
    @staticmethod
    def from_dict(data: Dict[str, Any]) -> "CapabilityMetadata":
        """Create CapabilityMetadata from dictionary (e.g., from JSON)."""
        return CapabilityMetadata(
            id=data.get("id", ""),
            name=data.get("name", ""),
            description=data.get("description", ""),
            type=CapabilityType(data.get("type", "unknown")) if isinstance(data.get("type"), str) else data.get("type", CapabilityType.UNKNOWN),
            entry_point=data.get("entry_point", ""),
            supported_languages=data.get("supported_languages", []),
            version=data.get("version", "1.0.0"),
            created_date=data.get("created_date", datetime.utcnow().isoformat()),
            last_modified=data.get("last_modified", datetime.utcnow().isoformat()),
            generated=data.get("generated", False),
            origin=data.get("origin"),
            failure_pattern=data.get("failure_pattern"),
            trigger_tasks=data.get("trigger_tasks", []),
            reuse_count=data.get("reuse_count", 0),
            test_coverage=data.get("test_coverage", 0.0),
            documentation_path=data.get("documentation_path", ""),
            metadata_path=data.get("metadata_path", ""),
            status=data.get("status", "active"),
            extra_metadata=data.get("extra_metadata", {}),
        )


@dataclass
class CapabilityQuery:
    """Query parameters for searching the capability registry."""
    
    capability_id: Optional[str] = None
    capability_type: Optional[str] = None  # "bug_detection", "parsing", etc.
    language: Optional[str] = None  # "python", "java", "javascript", etc.
    name_contains: Optional[str] = None
    generated_only: bool = False  # If True, only return generated capabilities
    seed_only: bool = False  # If True, only return seed (non-generated) capabilities
    status: Optional[str] = None  # "active", "deprecated", etc.
    min_test_coverage: float = 0.0  # Only return capabilities with coverage >= this
    sort_by: str = "id"  # "id", "reuse_count", "test_coverage", "created_date"
    sort_order: str = "asc"  # "asc" or "desc"
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert query to dictionary."""
        return asdict(self)


@dataclass
class CapabilityQueryResult:
    """Result of a capability registry query."""
    
    matched_count: int
    capabilities: List[CapabilityMetadata] = field(default_factory=list)
    query_time_ms: float = 0.0
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert result to dictionary."""
        return {
            "matched_count": self.matched_count,
            "capabilities": [cap.to_dict() for cap in self.capabilities],
            "query_time_ms": self.query_time_ms,
        }


@dataclass
class CapabilityReusageRecord:
    """Record of a capability being used (reused)."""
    
    capability_id: str
    timestamp: str = field(default_factory=lambda: datetime.utcnow().isoformat())
    task_id: str = ""
    success: bool = True
    execution_time_ms: float = 0.0
    notes: str = ""


@dataclass
class CapabilityRegistry:
    """
    In-memory capability registry that can be persisted to/loaded from JSON.
    This is the registry structure, not the registry manager.
    """
    
    version: str = "1.0.0"
    last_updated: str = field(default_factory=lambda: datetime.utcnow().isoformat())
    capabilities: List[CapabilityMetadata] = field(default_factory=list)
    usage_history: List[CapabilityReusageRecord] = field(default_factory=list)
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert entire registry to dictionary."""
        return {
            "version": self.version,
            "last_updated": self.last_updated,
            "capabilities": [cap.to_dict() for cap in self.capabilities],
            "usage_history": [
                {
                    "capability_id": usage.capability_id,
                    "timestamp": usage.timestamp,
                    "task_id": usage.task_id,
                    "success": usage.success,
                    "execution_time_ms": usage.execution_time_ms,
                    "notes": usage.notes,
                }
                for usage in self.usage_history
            ],
        }
    
    @staticmethod
    def from_dict(data: Dict[str, Any]) -> "CapabilityRegistry":
        """Create CapabilityRegistry from dictionary."""
        caps = [
            CapabilityMetadata.from_dict(cap_data)
            for cap_data in data.get("capabilities", [])
        ]
        usage = [
            CapabilityReusageRecord(
                capability_id=usage_data.get("capability_id", ""),
                timestamp=usage_data.get("timestamp", datetime.utcnow().isoformat()),
                task_id=usage_data.get("task_id", ""),
                success=usage_data.get("success", True),
                execution_time_ms=usage_data.get("execution_time_ms", 0.0),
                notes=usage_data.get("notes", ""),
            )
            for usage_data in data.get("usage_history", [])
        ]
        return CapabilityRegistry(
            version=data.get("version", "1.0.0"),
            last_updated=data.get("last_updated", datetime.utcnow().isoformat()),
            capabilities=caps,
            usage_history=usage,
        )
